//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImageScannerPicker.Properties {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ImageScannerPicker.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   A3과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string DIC_A3 {
            get {
                return ResourceManager.GetString("DIC_A3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A4과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string DIC_A4 {
            get {
                return ResourceManager.GetString("DIC_A4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ADF과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string DIC_ADF {
            get {
                return ResourceManager.GetString("DIC_ADF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Degree과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string DIC_Angle {
            get {
                return ResourceManager.GetString("DIC_Angle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Auto과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string DIC_Auto {
            get {
                return ResourceManager.GetString("DIC_Auto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   B3과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string DIC_B3 {
            get {
                return ResourceManager.GetString("DIC_B3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   B4과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string DIC_B4 {
            get {
                return ResourceManager.GetString("DIC_B4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   B5과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string DIC_B5 {
            get {
                return ResourceManager.GetString("DIC_B5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Black&amp;White과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string DIC_BlackWhite {
            get {
                return ResourceManager.GetString("DIC_BlackWhite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Both과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string DIC_Both {
            get {
                return ResourceManager.GetString("DIC_Both", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Brightness과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string DIC_Brightness {
            get {
                return ResourceManager.GetString("DIC_Brightness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   BusinessCard과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string DIC_BusinessCard {
            get {
                return ResourceManager.GetString("DIC_BusinessCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Color과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string DIC_Color {
            get {
                return ResourceManager.GetString("DIC_Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Flatbed과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string DIC_Flatbed {
            get {
                return ResourceManager.GetString("DIC_Flatbed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   GrayScale과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string DIC_GrayScale {
            get {
                return ResourceManager.GetString("DIC_GrayScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Letter과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string DIC_Letter {
            get {
                return ResourceManager.GetString("DIC_Letter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Manual과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string DIC_Manual {
            get {
                return ResourceManager.GetString("DIC_Manual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Single과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string DIC_Single {
            get {
                return ResourceManager.GetString("DIC_Single", resourceCulture);
            }
        }
    }
}
